"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/alocar/bloco/ HTTP/1.1" 200 4982
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/add/ HTTP/1.1" 200 4037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/add/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5381
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 6037
"GET /relatorio HTTP/1.1" 301 0
"GET /relatorio/ HTTP/1.1" 200 0
"GET /admin/ HTTP/1.1" 200 6386
"GET /admin/ HTTP/1.1" 200 6386
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /export/xls/ HTTP/1.1" 200 5632
"GET /admin/ HTTP/1.1" 200 6386
"GET /admin/ HTTP/1.1" 200 6386
"GET /admin/alocar/turma/ HTTP/1.1" 200 4280
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/turma/import/ HTTP/1.1" 200 3201
"GET /static/import_export/import.css HTTP/1.1" 304 0
"POST /admin/alocar/turma/import/ HTTP/1.1" 200 129
"GET /admin/alocar/turma/import/ HTTP/1.1" 200 3201
"POST /admin/alocar/turma/import/ HTTP/1.1" 200 14537
"POST /admin/alocar/turma/process_import/ HTTP/1.1" 302 0
"GET /admin/alocar/turma/ HTTP/1.1" 200 16408
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /listsalaturma/ HTTP/1.1" 200 22734
"GET /addsala/ HTTP/1.1" 200 8864
"POST /addsala/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 10434
"POST /addsala/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 12004
"POST /addsala/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 13574
"POST /addsala/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15145
"GET /altsala/4/ HTTP/1.1" 200 6284
"POST /altsala/4/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15144
"GET /listsalaturma/ HTTP/1.1" 200 27182
"GET /addhorario/ HTTP/1.1" 200 4460
"POST /addhorario/ HTTP/1.1" 200 5171
"POST /addhorario/ HTTP/1.1" 200 5882
"POST /addhorario/ HTTP/1.1" 200 6593
"POST /addhorario/ HTTP/1.1" 200 7304
"POST /addhorario/ HTTP/1.1" 200 8015
"GET /listsalaturma/ HTTP/1.1" 200 27392
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4233
"GET /addsala/ HTTP/1.1" 200 15144
"GET /altsala/1/ HTTP/1.1" 200 6283
"POST /altsala/1/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15140
"GET /altsala/2/ HTTP/1.1" 200 6283
"POST /altsala/2/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15136
"GET /altsala/3/ HTTP/1.1" 200 6283
"POST /altsala/3/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15132
"GET /altsala/4/ HTTP/1.1" 200 6283
"POST /altsala/4/ HTTP/1.1" 302 0
"GET /addsala/ HTTP/1.1" 200 15128
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5280
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5376
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5376
"GET /altalocacao/1/ HTTP/1.1" 200 5817
"POST /altalocacao/1/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5376
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 6403
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 8651
"GET /relatorio/ HTTP/1.1" 200 5066
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 8651
"GET /relatorio/ HTTP/1.1" 200 5066
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /relatorio/ HTTP/1.1" 200 5066
Acessaram a listagem de alocação
"GET /listalocacao/?varios=a100 HTTP/1.1" 200 5280
"GET /conturma/ HTTP/1.1" 200 52421
"GET /listsalaturma/ HTTP/1.1" 200 27376
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 8651
"GET /delalocacao/4/ HTTP/1.1" 200 3199
"POST /delalocacao/4/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /delalocacao/3/ HTTP/1.1" 200 3199
"POST /delalocacao/3/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 6403
"GET /delalocacao/2/ HTTP/1.1" 200 3199
"POST /delalocacao/2/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5280
"GET /delalocacao/1/ HTTP/1.1" 200 3199
"POST /delalocacao/1/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /conturma/ HTTP/1.1" 200 4396
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /conturma/ HTTP/1.1" 200 4396
Internal Server Error: /relatorio/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 25, in excelview
    return ExcelResponse(objs)
NameError: name 'objs' is not defined
"GET /relatorio/ HTTP/1.1" 500 69376
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /export/xls/ HTTP/1.1" 200 5632
Not Found: /relatorio/
"GET /relatorio/ HTTP/1.1" 404 5859
C:\Users\shaba\PycharmProjects\alocacao\alocar\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /relatorio/
"GET /relatorio/ HTTP/1.1" 404 5859
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5280
"GET /listsalaturma/ HTTP/1.1" 200 27376
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5280
"GET /conturma/ HTTP/1.1" 200 16405
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 5280
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 6403
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 6403
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 6403
"GET /conturma/ HTTP/1.1" 200 28411
"GET /usuarios/ HTTP/1.1" 200 2740
"GET /usuarios/ HTTP/1.1" 200 2740
"GET /usuarios/ HTTP/1.1" 200 2740
"GET /usuarios/ HTTP/1.1" 200 2826
"GET /conturma/ HTTP/1.1" 200 28411
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /conturma/ HTTP/1.1" 200 28411
"GET /conturma/ HTTP/1.1" 200 28411
"GET /listsalaturma/ HTTP/1.1" 200 27376
"POST /listsalaturma/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /usuarios/ HTTP/1.1" 200 2826
"GET /conturma/ HTTP/1.1" 200 40418
"GET /listsalaturma/ HTTP/1.1" 200 27376
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /altalocacao/5/ HTTP/1.1" 200 5817
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /listsalaturma/ HTTP/1.1" 200 27376
"GET /listsalaturma/ HTTP/1.1" 200 27376
"GET /listsalaturma/ HTTP/1.1" 200 27376
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /altalocacao/5/ HTTP/1.1" 200 5140
"POST /altalocacao/5/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7621
"GET /altalocacao/5/ HTTP/1.1" 200 5140
"POST /altalocacao/5/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7621
"GET /addturma/ HTTP/1.1" 200 27878
"GET /altturma/14/ HTTP/1.1" 200 7013
"GET /addturma/ HTTP/1.1" 200 27878
"GET /addhorario/ HTTP/1.1" 200 8015
"GET /addhorario/ HTTP/1.1" 200 8015
"GET /delhorario/5/ HTTP/1.1" 200 3255
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/5/ HTTP/1.1" 200 3255
"GET /delhorario/5/ HTTP/1.1" 200 3255
"GET /delhorario/5/ HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=bVI067rWQRvjy16VQ7tvTi8srxLXaOHrqCyqJOvYWrWZRae2Qh8VVMpfeOIL1Yb2 HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=ozuZ2BAb9jy712dMtIwsE3s8N3tByDgSDgkpFiEdfTZNkblTtSbSGxJVAkqppNKt HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=ClTOYQpVqLQ5qj9x7msghYiPcFgNUoOaR2JeBxtXwlhLJshE7w7GjszCZWdBLyiL HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=q9wNBq1GvGL4dk0VMpQ0vtl5lRq8XTL1FQmde75IBgcKwt82MzvqxXCS88nWO3fC HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=Bn5vXKRBnIHNwdxQeBYnJhaqUMCzf7cPQ4VVArVDti8tPmFXeLDNLLrdH3zn6hGq HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=IR6KzrNvqnjlcH7FLpUlNnIuLsKK5aSiXyWac8RxwXK1vQfMLzzLPRZhyJHyWkmT HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=k9WxcSTphvaCtn54EGIUAxBCky4AHd1dzQMXPzXrn5BiMwdbEQnkC1Sp7P1oynvO HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=oxPKx5Z8fd8vTvqI3us1vPTeaneRNpJ8DeFaaM3alNzbcEyP3E7rxja1XEbFEzdJ HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=9rMaR37ZfQur9NP3hG5tlhaPpuoWcxpMo8CAuKb1lqV7sWXahQKTnLrCcLlK3HTn HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=VxdevsF7LWOoKyTcd13vbuWBK6PlOEu0ae3E89J9Rwf43H1jdbIVdYdoxnM9FOYB HTTP/1.1" 200 3254
"GET /addhorario/ HTTP/1.1" 200 8015
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addhorario/ HTTP/1.1" 200 8015
"GET /delhorario/5/ HTTP/1.1" 200 3266
"GET /delhorario/5/?csrfmiddlewaretoken=dLtBILOrUHezbH29tTCumZ2ScRZ3W3eIssj1lsSt0hFfuQagt3hUotjFZ8WRNdIj HTTP/1.1" 200 3266
"GET /delhorario/5/?csrfmiddlewaretoken=xopSv0SMMDMBv2ShaXULon67iSrS2LgqM5fi8HWOSddhOb0oa7zbqRnU59oGTVK1 HTTP/1.1" 200 3266
"GET /delhorario/5/?csrfmiddlewaretoken=hP1QXOiB0TuWdKqKPpSm97UNAbubVSzRwwRgAvmD6tVCwTyRPzxMbBbAnsrZM23s HTTP/1.1" 200 3266
"GET /delhorario/5/?csrfmiddlewaretoken=H8N3j1sxLyAlaEAJOn5dUcIUPw0ud3z3WPDtWIwzR811tNIQOxKDWGZHCNXi4d3E HTTP/1.1" 200 3266
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/5/?csrfmiddlewaretoken=mYIU3Pcbi4BOmR5ksrKUQj9ogu4pg5F9BFykGwgdoE2uF0drsBpkSNqb3L1d7f9K HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=10KH4yTyC56qClMW7CExApHegTfc4k9kgHA7HfXAIFx6VuU37MjXCTY13ac0VuDV HTTP/1.1" 200 3254
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/5/?csrfmiddlewaretoken=10KH4yTyC56qClMW7CExApHegTfc4k9kgHA7HfXAIFx6VuU37MjXCTY13ac0VuDV HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=CTr3haMEoZhCh8DsDlkLauTARxSEVWoXRAhtURQGuzIiAhLzDvZbcYanEOPsM6Sy HTTP/1.1" 200 3254
"GET /addhorario/ HTTP/1.1" 200 8015
"GET /delhorario/5/ HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=YtZ1aFedNDSdDWfGT3dLPtP1aRCIH5RLdaPrNmifTdjTW5nNTdSbRX6OX8zwyflm HTTP/1.1" 200 3254
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/5/?csrfmiddlewaretoken=YtZ1aFedNDSdDWfGT3dLPtP1aRCIH5RLdaPrNmifTdjTW5nNTdSbRX6OX8zwyflm HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=sAzIxHOXqsCDL2rHWRdCKt0enlsQ91rOHhp8aoSZw23j4bzOW1S2MXh1aCpE0bVp HTTP/1.1" 200 3254
"GET /delhorario/5/?csrfmiddlewaretoken=sAzIxHOXqsCDL2rHWRdCKt0enlsQ91rOHhp8aoSZw23j4bzOW1S2MXh1aCpE0bVp HTTP/1.1" 200 3255
"POST /delhorario/5/?csrfmiddlewaretoken=sAzIxHOXqsCDL2rHWRdCKt0enlsQ91rOHhp8aoSZw23j4bzOW1S2MXh1aCpE0bVp HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 7304
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 7417
"GET /delhorario/1/ HTTP/1.1" 200 3255
"POST /delhorario/1/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 7417
"GET /delhorario/2/ HTTP/1.1" 200 3255
"POST /delhorario/2/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6593
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6706
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addhorario/ HTTP/1.1" 200 6593
"GET /delhorario/4/ HTTP/1.1" 200 3255
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6706
"GET /delhorario/3/ HTTP/1.1" 200 3255
"POST /delhorario/3/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6706
"GET /althorario/3/ HTTP/1.1" 200 3718
"POST /althorario/3/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6593
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addhorario/ HTTP/1.1" 200 6593
"GET /althorario/4/ HTTP/1.1" 200 3718
"POST /althorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6735
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addhorario/ HTTP/1.1" 200 6593
"GET /althorario/4/ HTTP/1.1" 200 3718
"POST /althorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6742
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6735
"GET /althorario/4/ HTTP/1.1" 200 3718
"POST /althorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6742
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addhorario/ HTTP/1.1" 200 6593
"GET /althorario/4/ HTTP/1.1" 200 3718
"POST /althorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6742
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6742
"GET /addhorario/ HTTP/1.1" 200 6593
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /althorario/4/ HTTP/1.1" 200 3718
"POST /althorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6742
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6751
"GET /delhorario/4/ HTTP/1.1" 200 3255
"POST /delhorario/4/ HTTP/1.1" 302 0
"GET /addhorario/ HTTP/1.1" 200 6751
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /addturma/ HTTP/1.1" 200 27878
"GET /addsala/ HTTP/1.1" 200 15128
"GET /addbloco/ HTTP/1.1" 200 5888
"GET /delbloco/5/ HTTP/1.1" 200 3231
"POST /delbloco/5/ HTTP/1.1" 302 0
"GET /addbloco/ HTTP/1.1" 200 6002
"GET /altbloco/5/ HTTP/1.1" 200 3749
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /altbloco/5/ HTTP/1.1" 200 3749
"POST /altbloco/5/ HTTP/1.1" 302 0
"GET /addbloco/ HTTP/1.1" 200 6040
"GET /delbloco/5/ HTTP/1.1" 200 3231
"POST /delbloco/5/ HTTP/1.1" 302 0
"GET /addbloco/ HTTP/1.1" 200 6040
"GET /admin/ HTTP/1.1" 200 8926
"GET /admin/ HTTP/1.1" 200 8926
"GET /admin/ HTTP/1.1" 200 8926
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5200
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/4/change/ HTTP/1.1" 200 4256
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/4/change/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5379
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8929
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 25107
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8929
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 25107
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/45/change/ HTTP/1.1" 200 5984
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/usuarios/user/1/change/ HTTP/1.1" 200 13448
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/usuarios/user/1/change/ HTTP/1.1" 302 0
"GET /admin/usuarios/user/ HTTP/1.1" 200 7198
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8934
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 25107
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=0 HTTP/1.1" 200 19089
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=2 HTTP/1.1" 200 10841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/?_changelist_filters=action__exact%3D2 HTTP/1.1" 200 5685
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/?_changelist_filters=action__exact%3D2 HTTP/1.1" 500 200350
"GET /admin/auditlog/logentry/add/?_changelist_filters=action__exact%3D2 HTTP/1.1" 200 5685
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/?_changelist_filters=action__exact%3D2 HTTP/1.1" 500 200378
"GET /admin/auditlog/logentry/add/?_changelist_filters=action__exact%3D2 HTTP/1.1" 200 5685
"GET /admin/auditlog/logentry/?action__exact=2 HTTP/1.1" 200 10841
"GET /admin/auditlog/logentry/45/change/?_changelist_filters=action__exact%3D2 HTTP/1.1" 200 6098
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/45/change/?_changelist_filters=action__exact%3D2 HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/?action__exact=2 HTTP/1.1" 200 11047
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/horario/2/change/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 9129
"GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 199432
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 199433
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5200
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/4/change/ HTTP/1.1" 200 4256
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/4/history/ HTTP/1.1" 200 2357
"GET /admin/ HTTP/1.1" 200 8964
"GET /admin/auditlog/logentry/45/change/ HTTP/1.1" 200 5984
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/45/delete/ HTTP/1.1" 200 3334
"POST /admin/auditlog/logentry/45/delete/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24781
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/10/change/ HTTP/1.1" 200 6923
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/turma/15/change/ HTTP/1.1" 200 8000
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/turma/15/change/ HTTP/1.1" 302 0
"GET /admin/alocar/turma/ HTTP/1.1" 200 16445
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8950
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=0 HTTP/1.1" 200 19089
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=2 HTTP/1.1" 200 10315
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=1 HTTP/1.1" 200 9547
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/?action__exact=0 HTTP/1.1" 200 19089
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8950
"GET /admin/auth/group/add/ HTTP/1.1" 200 8661
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8950
"GET /admin/alocar/turma/31/change/ HTTP/1.1" 200 8006
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/turma/31/change/ HTTP/1.1" 302 0
"GET /admin/alocar/turma/ HTTP/1.1" 200 16443
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/turma/31/change/ HTTP/1.1" 200 8006
"GET /admin/ HTTP/1.1" 200 8951
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1699
"GET /static/css/mdb.min.css.map HTTP/1.1" 200 319849
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1699
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 7525
"GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1699
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1850
"GET /static/admin/css/login.css HTTP/1.1" 200 1233
"GET /static/admin/css/base.css HTTP/1.1" 200 16378
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5862
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 8951
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/css/base.css HTTP/1.1" 200 8192
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/base.css HTTP/1.1" 500 59
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5862
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /favicon.ico HTTP/1.1" 500 59
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /admin/usuarios/user/ HTTP/1.1" 200 7017
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 200 7099
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
"GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
"GET /static/admin/js/actions.js HTTP/1.1" 200 6766
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/alocar/sala/ HTTP/1.1" 200 8961
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /usuarios/entrar/ HTTP/1.1" 200 2559
"GET /static/images/bg.jpg HTTP/1.1" 404 1663
"POST /usuarios/entrar/ HTTP/1.1" 302 0
"GET /usuarios/ HTTP/1.1" 200 2826
"GET /conturma/ HTTP/1.1" 200 40418
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 199330
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/auditlog/ HTTP/1.1" 200 2530
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/ HTTP/1.1" 200 2530
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/usuarios/user/ HTTP/1.1" 200 7017
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /admin/ HTTP/1.1" 200 8951
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/usuarios/user/1/change/ HTTP/1.1" 200 13448
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
"GET /static/admin/css/forms.css HTTP/1.1" 200 8518
"GET /static/admin/js/change_form.js HTTP/1.1" 200 712
"GET /static/admin/js/calendar.js HTTP/1.1" 304 0
"GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
"GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 24619
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/alocar/sala/ HTTP/1.1" 200 8961
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/assets/extra.css HTTP/1.1" 404 1672
Internal Server Error: /conturma/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'widget_tweaks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 45, in consultarTurmas
    return render(request, 'alocar/consultarturmas.html', context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'widget_tweaks' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap4
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
import_export_tags
l10n
log
static
staticfiles
tz
"GET /conturma/ HTTP/1.1" 500 164659
"GET /comum HTTP/1.1" 301 0
Internal Server Error: /comum/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 25, in comum
    return render(request, "alcoar:comum", context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: alcoar:comum
"GET /comum/ HTTP/1.1" 500 89154
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /comum/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 25, in comum
    return render(request, "alocar:comum", context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: alocar:comum
"GET /comum/ HTTP/1.1" 500 89289
C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /comum/ HTTP/1.1" 200 42401
"GET /comum/ HTTP/1.1" 200 41917
"GET /comum/ HTTP/1.1" 200 41917
"GET /comum/ HTTP/1.1" 200 42149
"GET /comum/ HTTP/1.1" 200 42905
Internal Server Error: /comum/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '{{alocar.action}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 25, in comum
    return render(request, "alocar/comum.html", context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{alocar.action}}' from '{{alocar.action}}'
"GET /comum/ HTTP/1.1" 500 218756
"GET /comum/ HTTP/1.1" 200 44225
Internal Server Error: /comum/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 25, in comum
    return render(request, "alocar/comum.html", context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 972, in do_if
    raise TemplateSyntaxError('Malformed template tag at line {0}: "{1}"'.format(token.lineno, token.contents))
django.template.exceptions.TemplateSyntaxError: Malformed template tag at line 71: "else alocar.action == 2"
"GET /comum/ HTTP/1.1" 500 190635
"GET /comum/ HTTP/1.1" 200 45108
"GET /comum/ HTTP/1.1" 200 45150
"GET /comum/ HTTP/1.1" 200 45258
"GET /comum/ HTTP/1.1" 200 46093
"GET /comum/ HTTP/1.1" 200 46101
"GET /comum/ HTTP/1.1" 200 46140
"GET /comum/ HTTP/1.1" 200 46104
"GET /comum/ HTTP/1.1" 200 46104
"GET /comum/ HTTP/1.1" 200 46104
"GET /comum/ HTTP/1.1" 200 46104
"GET /comum/ HTTP/1.1" 200 46104
"GET /comum/ HTTP/1.1" 200 64283
"GET /comum/ HTTP/1.1" 200 3927
Internal Server Error: /addhorario/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'widget_tweaks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 692, in addHorario
    return render(request, template_name, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'widget_tweaks' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap4
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
import_export_tags
l10n
log
static
staticfiles
tz
"GET /addhorario/ HTTP/1.1" 500 165158
"GET /addhorario/ HTTP/1.1" 200 6593
"POST /addhorario/ HTTP/1.1" 200 7304
"GET /comum/ HTTP/1.1" 200 5384
"GET /comum/ HTTP/1.1" 200 5124
"GET /comum/ HTTP/1.1" 200 5106
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/ HTTP/1.1" 200 8951
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6258
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198643
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.content_type_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.content_type_id
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198694
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
Internal Server Error: /admin/auditlog/logentry/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 339, in result_list
    'results': list(results(cl)),
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 315, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 306, in __init__
    super().__init__(*items)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 229, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    value = attr(obj)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\auditlog\mixins.py", line 52, in msg_short
    changes = json.loads(obj.changes)
  File "C:\Users\shaba\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"GET /admin/auditlog/logentry/ HTTP/1.1" 500 350046
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
Internal Server Error: /admin/auditlog/logentry/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 339, in result_list
    'results': list(results(cl)),
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 315, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 306, in __init__
    super().__init__(*items)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 229, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    value = attr(obj)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\auditlog\mixins.py", line 52, in msg_short
    changes = json.loads(obj.changes)
  File "C:\Users\shaba\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"GET /admin/auditlog/logentry/ HTTP/1.1" 500 348663
"GET /admin/ HTTP/1.1" 200 8966
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5200
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/add/ HTTP/1.1" 200 4037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/add/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5598
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8966
Internal Server Error: /admin/auditlog/logentry/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 339, in result_list
    'results': list(results(cl)),
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 315, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 306, in __init__
    super().__init__(*items)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 229, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    value = attr(obj)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\auditlog\mixins.py", line 52, in msg_short
    changes = json.loads(obj.changes)
  File "C:\Users\shaba\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"GET /admin/auditlog/logentry/ HTTP/1.1" 500 348945
"GET /admin/ HTTP/1.1" 200 8966
"GET /admin/alocar/turma/ HTTP/1.1" 200 16266
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/turma/add/ HTTP/1.1" 200 7698
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/turma/ HTTP/1.1" 200 16266
"GET /admin/ HTTP/1.1" 200 8966
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5417
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/add/ HTTP/1.1" 200 4037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/add/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5815
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 8968
"GET /admin/ HTTP/1.1" 500 59
Internal Server Error: /conturma/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'widget_tweaks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 45, in consultarTurmas
    return render(request, 'alocar/consultarturmas.html', context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'widget_tweaks' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap4
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
import_export_tags
l10n
log
static
staticfiles
tz
"GET /conturma/ HTTP/1.1" 500 164659
"GET /comum/ HTTP/1.1" 200 8504
Watching for file changes with StatReloader
"GET /comum/ HTTP/1.1" 200 8504
"GET /admin/ HTTP/1.1" 200 8968
"GET /admin/ HTTP/1.1" 200 8968
Internal Server Error: /admin/auditlog/logentry/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 339, in result_list
    'results': list(results(cl)),
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 315, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 306, in __init__
    super().__init__(*items)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 229, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\utils.py", line 271, in lookup_field
    value = attr(obj)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\auditlog\mixins.py", line 52, in msg_short
    changes = json.loads(obj.changes)
  File "C:\Users\shaba\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shaba\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"GET /admin/auditlog/logentry/ HTTP/1.1" 500 348945
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auditlog/logentry/ HTTP/1.1" 200 1886
"POST /admin/login/?next=/admin/auditlog/logentry/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198605
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/alocar/bloco/ HTTP/1.1" 200 3547
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/add/ HTTP/1.1" 200 4037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
Internal Server Error: /addsala/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'widget_tweaks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\alocar\views.py", line 217, in addSala
    return render(request, template_name, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'widget_tweaks' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap4
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
import_export_tags
l10n
log
static
staticfiles
tz
"GET /addsala/ HTTP/1.1" 500 171129
"GET /addsala/ HTTP/1.1" 200 8788
"GET /addbloco/ HTTP/1.1" 200 4442
"POST /addbloco/ HTTP/1.1" 200 5165
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6244
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6325
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5898
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198621
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/ HTTP/1.1" 200 6411
"GET /admin/ HTTP/1.1" 500 59
"GET /comum/ HTTP/1.1" 200 5100
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/css/mdb.min.css HTTP/1.1" 200 275886
"GET /static/css/style.css HTTP/1.1" 200 1158
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 159521
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 6029
"GET /listalocacao/ HTTP/1.1" 302 0
"GET /usuarios/entrar/?next=/listalocacao/ HTTP/1.1" 200 2559
"GET /static/assets/custom.min.css HTTP/1.1" 200 2531
"GET /static/assets/bootstrap.min.css HTTP/1.1" 200 127381
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 8192
"GET /static/css/bootstrap.min.css HTTP/1.1" 500 59
"GET /static/css/style.css HTTP/1.1" 200 1158
"GET /static/css/style.css HTTP/1.1" 500 59
"GET /static/assets/style.css HTTP/1.1" 200 1380
"GET /static/assets/estilo.css HTTP/1.1" 200 913
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 6029
"GET /favicon.ico HTTP/1.1" 500 59
"GET /static/images/bg.jpg HTTP/1.1" 404 1663
"POST /usuarios/entrar/?next=/listalocacao/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 6029
"GET /addhorario/ HTTP/1.1" 200 4460
"POST /addhorario/ HTTP/1.1" 200 5171
"GET /delhorario/1/ HTTP/1.1" 200 3267
"GET /delhorario/1/ HTTP/1.1" 200 3274
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/css/mdb.min.css HTTP/1.1" 304 0
"GET /static/css/style.css HTTP/1.1" 304 0
"GET /delhorario/1/ HTTP/1.1" 200 3285
"GET /static/css/style.css HTTP/1.1" 304 0
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/css/mdb.min.css HTTP/1.1" 304 0
"GET /delhorario/1/ HTTP/1.1" 200 3290
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/css/style.css HTTP/1.1" 304 0
"GET /static/css/mdb.min.css HTTP/1.1" 304 0
"GET /delhorario/1/ HTTP/1.1" 200 3294
"GET /static/css/mdb.min.css HTTP/1.1" 304 0
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/css/style.css HTTP/1.1" 304 0
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 6411
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/css/base.css HTTP/1.1" 200 16378
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6839
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
"GET /static/admin/js/core.js HTTP/1.1" 200 7099
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
"GET /static/admin/js/actions.js HTTP/1.1" 200 6766
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auditlog/logentry/ HTTP/1.1" 200 1886
"GET /static/admin/css/base.css HTTP/1.1" 200 16378
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/login.css HTTP/1.1" 200 1233
Not Found: /favicon.ico
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /favicon.ico HTTP/1.1" 404 6029
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"POST /admin/login/?next=/admin/auditlog/logentry/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6839
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/js/actions.js HTTP/1.1" 200 6766
"GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
"GET /static/admin/js/core.js HTTP/1.1" 200 7099
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/css/forms.css HTTP/1.1" 200 8518
"GET /static/admin/js/change_form.js HTTP/1.1" 200 712
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
"GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198658
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198660
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/ HTTP/1.1" 200 6411
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 6411
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6839
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6325
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7040
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1088, in save_model
    obj.save()
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\shaba\ProjetosDjango\alocacao\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auditlog_logentry.action
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 500 198660
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 7019
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6839
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6832
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6330
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7042
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/2/change/ HTTP/1.1" 200 6346
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/2/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7046
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 7939
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5655
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5903
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5903
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/None/change/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 9203
"GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5655
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7039
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6841
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 159521
"GET /static/css/mdb.min.css HTTP/1.1" 200 275886
"GET /static/css/style.css HTTP/1.1" 200 1158
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 9139
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6846
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6846
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/2/change/ HTTP/1.1" 200 6351
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/2/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7051
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6335
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/delete/ HTTP/1.1" 200 3320
"GET /static/admin/js/cancel.js HTTP/1.1" 200 409
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6335
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6579
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 7047
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\ProjetosDjango\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /listalocacao/ HTTP/1.1" 302 0
"GET /usuarios/entrar/?next=/listalocacao/ HTTP/1.1" 200 2559
"GET /static/images/bg.jpg HTTP/1.1" 404 1663
"POST /usuarios/entrar/?next=/listalocacao/ HTTP/1.1" 302 0
Acessaram a listagem de alocação
"GET /listalocacao/ HTTP/1.1" 200 4157
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 500 136188
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 500 136188
"GET / HTTP/1.1" 200 2005
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 500 136188
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 500 136323
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
Internal Server Error: /admin/auditlog/logentry/add/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (created, msg, resource_url, user_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 500 136188
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/ HTTP/1.1" 200 6074
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4044
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5647
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 4242
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 6403
"GET /admin/alocar/bloco/ HTTP/1.1" 200 3547
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/alocar/bloco/add/ HTTP/1.1" 200 4037
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/add/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5163
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 6686
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6244
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\mixins.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6247
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6247
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6328
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6448
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/add/ HTTP/1.1" 200 5653
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/add/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6445
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2005
"GET /static/assets/pessoal.css HTTP/1.1" 404 1678
"GET /static/assets/extra.css HTTP/1.1" 404 1672
"GET /admin/ HTTP/1.1" 200 7294
"GET /admin/ HTTP/1.1" 200 7294
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6247
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
Internal Server Error: /admin/auditlog/logentry/1/change/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\forms\models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (msg, user_url, created, resource_url) specified for LogEntry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (msg, user_url, created, resource_url) specified for LogEntry. Check fields/fieldsets/exclude attributes of class LogEntryAdmin.
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 500 137016
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6328
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6448
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6247
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6335
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6144
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5417
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6144
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6388
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5417
"GET /admin/ HTTP/1.1" 200 8463
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5216
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6144
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/auditlog/logentry/1/change/ HTTP/1.1" 302 0
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5417
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6144
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/auditlog/logentry/1/change/
Traceback (most recent call last):
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Users\shaba\PycharmProjects\alocacao\venv\lib\site-packages\django\contrib\admin\options.py", line 676, in get_form
    if change and hasattr(request, 'user') and not self.has_change_permission(request, obj):
TypeError: has_change_permission() takes 2 positional arguments but 3 were given
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 500 115594
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6071
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5218
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6071
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5218
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6071
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5218
"GET /admin/alocar/bloco/1/change/ HTTP/1.1" 200 4256
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"POST /admin/alocar/bloco/1/change/ HTTP/1.1" 302 0
"GET /admin/alocar/bloco/ HTTP/1.1" 200 5161
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 9056
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 5218
C:\Users\shaba\PycharmProjects\alocacao\venv\Lib\site-packages\auditlog\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6125
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/ HTTP/1.1" 200 9056
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6125
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/1/change/ HTTP/1.1" 200 6186
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
"GET /admin/auditlog/logentry/ HTTP/1.1" 200 6125
"GET /admin/jsi18n/ HTTP/1.1" 200 7144
